FROM amazoncorretto:11
COPY metadata-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/metadata/metadata-1.0-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8080/tcp
CMD java -jar opt/metadata/metadata-1.0-SNAPSHOT-jar-with-dependencies.jar