version: "3"
services:
  crawler:
    build: /crawler
    volumes:
      - app:/app
  indexer:
    build: /indexer
    volumes:
      - app:/app
      - invertedIndexDatamart:/invertedIndexDatamart
  metadata:
    build: /metadata
    volumes:
      - app:/app
      - metadataDatamart:/metadataDatamart
  webservice:
    build: /webservice
    volumes:
      - app:/app
      - invertedIndexDatamart:/invertedIndexDatamart:ro
      - metadataDatamart:/metadataDatamart:ro
    ports:
      - "8080:8080"
volumes:
  app:
    external: true
  invertedIndexDatamart:
    external: true
  metadataDatamart:
    external: true