version: "3"
services:
  crawler:
    build: /crawler
    volumes:
      - app:/app
  indexer:
    build: /indexer
    volumes:
      - app:/app
  metadata:
    build: /metadata
    volumes:
      - app:/app
  webservice:
    build: /webservice
    volumes:
      - app:/app
    ports:
      - "8080:8080"
volumes:
  app:
    external: true