FROM amazoncorretto:11
VOLUME /datalake
COPY crawler-1.0-SNAPSHOT-jar-with-dependencies.jar /app/crawler-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java", "-jar", "/app/crawler-1.0-SNAPSHOT-jar-with-dependencies.jar"]