FROM amazoncorretto:11
COPY crawler-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/crawler/crawler-1.0-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8080/tcp
CMD java -jar opt/crawler/crawler-1.0-SNAPSHOT-jar-with-dependencies.jar