FROM amazoncorretto:11
COPY indexer-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/indexer/indexer-1.0-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8080/tcp
CMD java -jar opt/indexer/indexer-1.0-SNAPSHOT-jar-with-dependencies.jar