version: '3'

services:
  webservice:
    build: ../webservice
    volumes:
      - app:/app
    ports:
      - "5000:8080"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"


volumes:
  app:
    external: true
