FROM amazoncorretto:11
COPY webservice-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/webservice/webservice-1.0-SNAPSHOT-jar-with-dependencies.jar
EXPOSE 8080/tcp
CMD java -jar opt/webservice/webservice-1.0-SNAPSHOT-jar-with-dependencies.jar